name: Run Java Program

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK *
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8' # Specify your Java version
        distribution: 'temurin' # Choose the distribution (e.g., temurin, zulu, adopt)

    # Step 3: Compile the Java program
    - name: Run Java Program
      run: |
        cd  src/main/java/com/example/App.java
        javac src/main/java/com/example/App.java
    
    # Step 4: Run the java program
    - name: Run Java Program
      run: |
      cd src/main/java/com/example/App.java
      ls
      java com.example.App
